# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: perlcritic
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  perlcritic:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: Difegue/action-perlcritic@master
        with:
          args: '--exclude=strict --exclude=require **.pl **/*.pl'
